### ISSUE TITLE
Detect of Alto without <style> values and lang attribute for <p> and <html> elements

### ISSUE THREAD

**Issue by aamodio** [filak/hOCR-to-ALTO#8] opened 2018-12-05 17:43 UTC
Hi,
the script "alto2hocr" is not able to detect when an ALTO file has no <Styles> values (empty).
I'm using an application to extract OCR in ALTO format that doesn't export font styles information.

There is also an issue in extracting the language values for <p> and <HTML> elements.
See file in attach.

Thank you very much.

A.

[alto_sample.xml.zip](https://github.com/filak/hOCR-to-ALTO/files/2649893/alto_sample.xml.zip)

**Comment by filak** [comment] 2018-12-05 22:14
OK, let's separate this:

1. The xml:lang and lang attributes - I will try to fix it so the value is preserved

2. What do you mean by "not able to detect..." - what should be the expected behavior ?

3. If there are no Styles attributes in your ALTO - what the stylesheet should do about it ?

What is your use case - what you are going to do with the hOCR files?

**Comment by filak** [comment] 2018-12-06 13:44
I have done some updates. Please test if the output is better now.

**Comment by filak** [comment] 2018-12-11 20:35
I am closing this since there is no feedback.

**Comment by aamodio** [comment] 2018-12-11 20:44
Sorry Filak,
I’m seeing your reply only now.
I’ll test it in few days.
A.

**Comment by aamodio** [comment] 2018-12-11 21:11
Hi Filak,

> What do you mean by "not able to detect..." - what should be the expected behavior ?

When ALTO files has no <styles> sub-elements, the XSLT outputs invalid <span> element because attributes "x_font" and "x_size" are empty. It shouldn't output these two attributes.
Example: <span ... x_font="" x_size=""> ->> <span ... >

> What is your use case - what you are going to do with the hOCR files?

I'm using the hOcr file to track the words coordinates in a search system

The lang issue is solved.

Thanks.
A.

**Comment by filak** [comment] 2018-12-11 23:32
There is nothing bad with the empty elements IMHO.

http://kba.github.io/hocr-spec/1.2/

**Comment by aamodio** [comment] 2018-12-12 06:09
Yes but x_font and x_size (I assumed that  values for those attributes are taken from master styles element but maybe I’m wrong) cannot be empty. The hOCR xml file doesn’t validate.
Thanks,
A.

**Comment by filak** [comment] 2018-12-12 07:21
OK, I'll try to handle this.

**Comment by aamodio** [comment] 2018-12-12 07:30
Thanks Filak.
A.

**Comment by filak** [comment] 2018-12-12 08:01
Fixed with https://github.com/filak/hOCR-to-ALTO/commit/e9c3f56db39da95195eef3ba103a8adcf07a5ddc

**Closed as completed by filak** 2018-12-12 08:01 UTC
Labels: bug, enhancement
